spring:
  application:
    name: pcc-service
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    password: ${PASS}
    platform: postgres
    url: jdbc:postgresql://localhost:5432/pcc
    username: postgres
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
jwt:
  secret: security

server:
  port: 8092
  servlet:
    context-path: /pcc

#eureka:
#  client:
#    service-url:
#      default-zone: http://eureka:password@localhost:8761/eureka

issuer-bank:
  pay: 'http://localhost:8099/bank2/accounts/issuerBankPayment'

bank1-application:
  backend: 'http://localhost:8090/bank1/accounts/issuerBankPayment'
  pan: '525150'

bank2-application:
  backend: 'http://localhost:8099/bank2/accounts/issuerBankPayment'
  pan: '987654'

