spring:
  application:
    name: bank2-service
  main:
    allow-circular-references: true
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    password: ${PASS}
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bank2
    username: postgres
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true


jwt:
  secret: security

server:
  port: 8099
  servlet:
    context-path: /bank2

bank:
  name: 'Bank 2'
  pan: 987654
  frontend:
    url: 'http://localhost:5000/'
    credit-card-data-module: 'credit-card'
    qr-code: 'qr-code'

psp:
  finish-payment: 'http://localhost:8000/bank-service/credit-cards/finishPayment'

pcc:
  pcc-request: 'http://localhost:8092/pcc/request/validateAndRedirect'