spring:
  application:
    name: bank2-service
  main:
    allow-circular-references: true
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    password: ${PASS}
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bank2
    username: postgres
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true


jwt:
  secret: security

server:
  port: 8099
  servlet:
    context-path: /bank2
  ssl:
    key-store: classpath:local-ssl.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: local_ssl

bank:
  pan: 987654
  frontend:
    url: 'http://localhost:3000/'
    credit-card-data-module: 'credit-card'

psp:
  finish-payment: 'http://localhost:8000/bank-service/credit-cards/finishPayment'

pcc:
  pcc-request: 'http://localhost:8092/pcc/request/validateAndRedirect'